<?php
if(!defined('TIDY_HTML')){
	define('TIDY_HTML', true);
}

if(!defined('CHAR_SET')){
	define('CHAR_SET', 'UTF-8');
}

if(!defined('USE_EXTERNAL_SKINS')){
	define('USE_EXTERNAL_SKINS', false);
}

if(!defined('SKIN')){
	define('SKIN', false);
}

if(!defined('SKIN_INHERITS_CSS')){
	define('SKIN_INHERITS_CSS', false);
}

if(!defined('SKIN_EXTENDS')){
	define('SKIN_EXTENDS', false);
}

if(!defined('SKIN_FOOTER_TEXT')){
	define('SKIN_FOOTER_TEXT', '');
}

if(!defined('ALLOW_REWRITE')){
	define('ALLOW_REWRITE', true);
}

if(!defined('LOGIN_BACKEND')){
	define('LOGIN_BACKEND', 'default');
}